# Generated by Django 5.0.4 on 2024-07-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=25)),
                ('tg_id', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=50)),
                ('gps_in', models.CharField(blank=True, max_length=250, null=True)),
                ('address_in', models.CharField(blank=True, max_length=250, null=True)),
                ('date_in', models.DateTimeField(blank=True, null=True)),
                ('clock_in', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_out', models.CharField(blank=True, max_length=250, null=True)),
                ('address_out', models.CharField(blank=True, max_length=250, null=True)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'attendances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'network_gps',
                'managed': False,
            },
        ),
    ]
